#%RAML 1.0 DataType
type: object
properties:
  status:
    enum: [Available , Unavailable]
    description: 
  timestamp:
    type: string
    description: Recupera a data e hora do Salesforce (fuso horário Hora Universal Coordenada (UTC))
  api:
    type: string
    description: Nome da API
  version:
    type: string
    description: Versão da API

examples:
  status: !include ../../examples/general/status.raml