#%RAML 1.0 NamedExample
value:
  id: a3317cd7-e86e-462d-8afd-914ff746ed22
  created: 2021-08-12T10:01:01.947Z
  externalCode: "9938"
  status: Completed
  links: 
    -
      rel: transactions
      href: /transactions/a3317cd7-e86e-462d-8afd-914ff746ed22
      method: GET