#%RAML 1.0 NamedExample
value:
  items:
    -
      applicationName: "Mulesoft API"
      className: "Salesforce System API"
      logDetail: "Failed to insert records"
      logLevel: "ERROR"
      logType: ""
      objectId: ""
      objectName: "Account"
    -
      applicationName: "Mulesoft API"
      className: "Salesforce System API"
      logDetail: "Failed to insert records"
      logLevel: "ERROR"
      logType: ""
      objectId: ""
      objectName: "Account"