#%RAML 1.0 NamedExample
value:
  lineEnding: "CRLF"
  numberRecordsFailed: 0
  externalIdFieldName: "Codigo_do_produto__c"
  numberRecordsProcessed: 0
  errorMessage: null
  systemModstamp: "2021-09-02T16:43:57.000+0000"
  apiActiveProcessingTime: 0
  concurrencyMode: "Parallel"
  retries: 0
  apexProcessingTime: 0
  apiVersion: "50.0"
  createdDate: "2021-09-02T16:43:56.000+0000"
  id: "75001000001s3i3AAA"
  state: "UploadComplete"
  jobType: "V2Ingest"
  totalProcessingTime: 0
  contentType: "CSV"
  operation: "upsert"
  createdById: "00501000001k0CEAAY"
  object: "Account"
  columnDelimiter: "COMMA"