#%RAML 1.0 NamedExample
value:
  status: Available
  timestamp: "2021-08-14T02:02:55.447"
  api: "Experience API"
  version: "1.0.0"
  connectedAPIs:
  -
    status: Available
    timestamp: "2021-08-14T02:02:55.447"
    api: "Proccess API"
    version: "1.0.0"
    connectedAPIs: 
    -
      status: Available
      timestamp: "2021-08-14T02:02:55.447"
      api: "System API"
      version: "1.0.0"