#%RAML 1.0 NamedExample
value:
  id: null
  items:
    -
      exception: null
      message: null
      payload:
        created: false
        success: true
        id: "a69010000009EM2AAM"
        errors: []
      id: "a69010000009EM2AAM"
      successful: true
      statusCode: null
    - 
      exception: null
      message: null
      payload:
        created: false
        success: true
        id: "a69010000009EM2AAM"
        errors: []
      id: "a69010000009EM2AAM"
      successful: true
      statusCode: null
  successful: true