#%RAML 1.0 NamedExample
value:
  Resultados:
  -
    id_produto: 1
    nome_produto: "video-game"
    valor_produto: "1000,00"
    data_compra: "2020-12-12 00:00:00.000"
    id_fabricante: 1
    Id?: ""
  totalRecords: 1