#%RAML 1.0 Library
types:
  customErrorMessage: !include ../datatypes/customErrorMessage.raml
  transactionId: !include ../datatypes/transactionId.raml
traits:
  security: !include ../traits/security.raml
  pagination: !include ../traits/pagination.raml
  date: !include ../traits/date.raml