#%RAML 1.0 DataType
type: object
description: Fabricante
properties:
  Resultados:
    type: array
    items:
      type: object
      properties:
        id_fabricante: number
        nome_fabricante: string
        Id?: string | nil

  totalRecords: number
  
examples: !include ../../examples/database/db_manufacturer.raml