#%RAML 1.0 DataType
type: object
description: Fabricante
properties:
  Codigo_da_Fabricante__c: number
  Name: string
  Id?: string | nil
  
examples: !include ../../examples/salesforce/sf_manufacturer.raml